# **Pre-processing Dataset**
> Pre-processing data text (Valid or Not)

In [13]:
# !pip install modin
# !pip install dask[dataframe]

INFO: pip is looking at multiple versions of dask-expr to determine which version is compatible with other requirements. This could take a while.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 243.2/243.2 kB 4.5 MB/s eta 0:00:00


In [19]:
# import modin.pandas as pd # Large Dataset
# import dask.dataframe as dd # Large Dataset (offline or downloaded data)
import pandas as pd
import numpy as np

In [21]:
dataset_1 = "https://raw.githubusercontent.com/sains-data/MentiChat/refs/heads/main/data/New_Cons.csv"
dataset_2 = "https://raw.githubusercontent.com/sains-data/MentiChat/refs/heads/main/data/data_olip.csv"

# Mengatur tampilan agar teks panjang terlihat lengkap (Untuk dataset teks panjang)
pd.set_option('display.max_colwidth', None)

# Pembacaan dataset (Pandas Dataframe)
df = pd.read_csv(dataset_1)
df2 = pd.read_csv(dataset_2)

In [41]:
print(f"Panjang dataset 1 : {len(df)} baris")
print(f"Panjang dataset 2 : {len(df2)} baris")

Panjang dataset 1 : 11017 baris
Panjang dataset 2 : 25000 baris


In [44]:
# Menunjukan sampel data secara acak sebanyak 5 buah dari data 1
df.sample(5)

Pertanyaan  \
8627                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      pengalaman pahit yang saya alami saat tumbuh dewasa membuat saya sulit mempercayai orang lain hal itu meninggalkan bekas luka mendalam yang saya bawa bahkan dalam hubungan saya saat ini   
620                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   putri saya ada di sekolah dasar nanti  dia tidak bisa mewarnai di garis  katakatanya tersembunyi bersama ketika dia menulis kecuali ada ruang besar atau dia melewatkan garis   
7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     aku sedang melalui beberapa hal dengan perasaanku dan diriku sendiri   saya hampir tidak tidur dan tidak melakukan apa pun selain memikirkan betapa saya tidak berharga dan betapa saya tidak seharusnya berada di sini   saya belum pernah mencoba atau berpikir untuk bunuh diri   saya selalu ingin memperbaiki masalah saya  tapi saya tidak pernah sempat melakukannya   bagaimana saya bisa mengubah perasaan saya yang tidak berharga bagi semua orang   
10149                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             saya percaya hal ini akan membawa rasa keterhubungan terkadang kesedihan dapat membuat kita merasa terisolasi dan sendirian tetapi dengan membenamkan diri dalam kenangan ini saya dapat mengingatkan diri saya bahwa cinta melampaui kehadiran fisik ini akan membantu saya menemukan penghiburan dan terus memelihara cinta yang masih ada dalam diri saya dari   
4322   saya punya anak dengan ibu bayi saya  dia bekerja  saya menjaga putra kami  dia bilang dia tidak selingkuh  aku

In [53]:
# Menunjukan sampel data secara acak sebanyak 5 buah dari data 2
df2.sample(5)

Question  \
16687                         Hai, saya harap Anda baik-baik saja. Saya merasa sangat kesal akhir-akhir ini, terutama karena penolakan terus-menerus yang saya hadapi di tempat kerja. Ini benar-benar berdampak buruk pada saya, dan saya tidak yakin bagaimana cara mengatasi stres ini.   
13316                          Hai, saya harap Anda baik-baik saja hari ini. Aku merasa sedikit mati rasa akhir-akhir ini, seperti aku melakukan apa yang aku lakukan tetapi tidak benar-benar merasakan banyak kegembiraan. Sepertinya aku kehilangan kendali atas kebahagiaanku sendiri.   
15418  Hai, saya harap Anda baik-baik saja. Saya ingin berbicara dengan Anda tentang sesuatu yang ada di pikiran saya akhir-akhir ini. Saya telah berjuang melawan kecanduan, dan hal itu memengaruhi kebahagiaan saya secara keseluruhan serta kemampuan saya untuk fokus pada pekerjaan.   
24159                                                                                                         Sejujurnya, saya belum terlalu memikirkannya. Tapi saya kira menetapkan batasan bisa menjadi pilihan. Sulit jika kehadirannya mendominasi, selalu membuat suaranya didengar.   
15223                                                                                   Hai, saya harap Anda baik-baik saja. Saya ingin berbicara dengan seseorang tentang kesedihan saya dan trauma yang saya bawa selama ini. Rasanya seperti beban berat yang tidak bisa saya lepaskan.   

                                                                                                                                                                                                                                                                                                                                                          Response  \
16687                                                                                                                         Hai, saya di sini untuk mendengarkan dan membantu Anda melalui ini. Sepertinya stres yang berhubungan dengan pekerjaan menyulitkan Anda, khususnya perasaan penolakan. Bisakah Anda ceritakan lebih banyak tentang apa yang terjadi?   
13316                                                                                                              Halo, senang mendengar pendapat Anda. Saya di sini untuk membantu Anda mengeksplorasi perasaan mati rasa ini dan membantu Anda mendapatkan kembali kendali atas kebahagiaan Anda. Bisakah Anda ceritakan lebih banyak tentang apa yang terjadi?   
15418  Hei, aku sangat senang kamu menghubungiku. Dibutuhkan banyak keberanian untuk mengakui tantangan yang kita hadapi. Saya di sini untuk mendengarkan dan mendukung Anda melalui perjalanan ini. Bisakah Anda ceritakan lebih banyak tentang apa yang secara spesifik Anda alami sehubungan dengan kecanduan Anda dan bagaimana dampaknya terhadap hidup Anda?   
24159                                                                                       Sangat dapat dimengerti bahwa menetapkan batasan mungkin sulit mengingat dominasinya. Namun, menemukan cara untuk melindungi kesejahteraan Anda sendiri sangatlah penting. Apakah ada anggota keluarga atau teman lain yang dapat memberikan dukungan selama masa ini?   
15223                                                                                                                                            Halo, saya di sini untuk mendengarkan dan mendukung Anda. Saya penasaran untuk memahami lebih jauh tentang kesedihan dan trauma yang Anda alami. Bisakah Anda ceritakan lebih banyak tentang apa yang Anda alami?   

       token_question  
16687              37  
13316              35  
15418              40  
24159              21  
15223              30

## **Melihat rata-rata token dari setiap data**
> Untuk menentukan dimensi dan menentukan token embedding

In [ ]:
# Menghitung token didalam sebuah data
def count_tokens(text):
  """Counts the number of tokens in a given text string."""
  if isinstance(text, str):
    return len(text.split())
  else:
    return 0

### **Data 1 (Gede)**

In [48]:
# Apply the function to the 'Pertanyaan' column
df['token_question'] = df['Pertanyaan'].apply(count_tokens)

# Calculate the average number of tokens per row
average_tokens_per_row = df['token_question'].mean()
max_token_per_row = df['token_question'].max()
print(f"Rata-rata token per baris: {average_tokens_per_row} token")
print(f"Max token per baris: {max_token_per_row} token")


for column in df.columns:
    if pd.api.types.is_string_dtype(df[column]): # checking if column is string
      df[f'{column}_token_count'] = df[column].apply(count_tokens)
      average_tokens_per_column = df[f'{column}_token_count'].mean()
      print(f"Rata-rata token untuk kolom '{column}': {average_tokens_per_column} token")

Rata-rata token per baris: 44.815013161477715 token
Max token per baris: 460 token
Rata-rata token untuk kolom 'Pertanyaan': 44.815013161477715 token
Rata-rata token untuk kolom 'Tanggapan': 100.27575565035853 token


### **Data 2 (Olip)**

In [55]:
# Apply the function to the 'Pertanyaan' column
df2['token_question'] = df2['Question'].apply(count_tokens)

# Calculate the average number of tokens per row
average_tokens_per_row = df2['token_question'].mean()
max_token_per_row = df2['token_question'].max()
print(f"Rata-rata token per baris: {average_tokens_per_row} token")
print(f"Max token per baris: {max_token_per_row} token")

# Diterapkan pada semua kolom
for column in df2.columns:
    if pd.api.types.is_string_dtype(df2[column]): # checking if column is string
      df2[f'{column}_token_count'] = df2[column].apply(count_tokens)
      average_tokens_per_column = df2[f'{column}_token_count'].mean()
      print(f"Rata-rata token untuk kolom '{column}': {average_tokens_per_column} token")

Rata-rata token per baris: 34.16628 token
Max token per baris: 157 token
Rata-rata token untuk kolom 'Question': 34.16628 token
Rata-rata token untuk kolom 'Response': 37.19192 token


**Analisis**
---
Untuk laporan awal dari dataset masing-masing data :

**Dataset 1 (Gede)**
```
Rata-rata token per baris: 44.815013161477715 token
Max token per baris: 460 token
Rata-rata token untuk kolom 'Pertanyaan': 44.815013161477715 token
Rata-rata token untuk kolom 'Tanggapan': 100.27575565035853 token
```

**Dataset 2 (Olip)**
```
Rata-rata token per baris: 34.16628 token
Max token per baris: 157 token
Rata-rata token untuk kolom 'Question': 34.16628 token
Rata-rata token untuk kolom 'Response': 37.19192 token
```